const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {shareContent}=require('../shared/sharing.mjs');
(async()=>{
 const fixture=JSON.parse(await fs.readFile('.test-data/fixture-path.json','utf8')),data=path.resolve('.test-data','sharing-ui-'+Date.now());await fs.mkdir(data,{recursive:true});
 const file=path.join(data,'project.cvcreator'),project={version:1,name:'Kung Pow collection',packTitle:'Kung Pow Favorites',author:'Pack Maker',media:{path:fixture.mkv,duration:8.021,audioIndex:1},scenes:[{id:'first',name:'Intro',start:2,end:6,clips:[{id:'one',start:.5,end:2,caption:"That's a lot of nuts!",character:'Vendor'},{id:'two',start:1,end:2.5,caption:'Four bucks baby.',character:'Vendor'},{id:'three',start:2,end:3,caption:'Hey!',character:'Customer'}]}]};await fs.writeFile(file,JSON.stringify(project));
 const launch=process.env.CV_PACKAGED_EXE?{executablePath:path.resolve(process.env.CV_PACKAGED_EXE),args:[]}:{args:[path.resolve('.')]},app=await electron.launch({...launch,env:{...process.env,CV_TEST_DATA:data}});
 try{
  const page=await app.firstWindow(),errors=[];page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));const button=name=>page.getByRole('button',{name,exact:true});
  await page.getByText('FFmpeg ready',{exact:false}).waitFor();assert.equal(await button('Reddit').isDisabled(),true);
  // Capture native clipboard writes without replacing the user's actual clipboard.
  await app.evaluate(({dialog,clipboard},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});dialog.showMessageBox=async()=>({response:1});clipboard.write=value=>global.__shareClipboard=value;clipboard.writeText=text=>global.__shareClipboard={text};},file);
  await button('Open').click();await page.locator('.line-row').last().waitFor();
  const exportBox=await button('Export collection').boundingBox(),shareBox=await button('Reddit').boundingBox();assert.ok(shareBox.y>exportBox.y);
  await button('Reddit').click();await page.getByRole('dialog',{name:'Share collection'}).waitFor();assert.equal(await page.getByRole('tab',{name:'Reddit'}).getAttribute('aria-selected'),'true');
  await page.getByLabel('Share introduction').fill('A scene collection for everyone.');await page.getByLabel('Share download link').fill('https://example.com/kung-pow.zip');
  let body=await page.getByLabel('Reddit share text').inputValue();assert.match(body,/Kung Pow Favorites/);assert.match(body,/9 words/);assert.ok(body.includes('| Vendor | 1 | 2 | 8 | 00:02\\.0 |'));assert.ok(!body.includes(fixture.mkv));
  await button('Copy title').click();await button('Title copied').waitFor();assert.deepEqual(await app.evaluate(()=>global.__shareClipboard),{text:'Kung Pow Favorites'});
  await button('Copy body').click();await button('Copied').waitFor();assert.equal((await app.evaluate(()=>global.__shareClipboard)).text,body);
  await page.getByRole('tab',{name:'Discord'}).click();await page.getByLabel('Share introduction').fill('A longer introduction. '.repeat(220));await page.getByLabel('Discord message').waitFor();
  const count=await page.getByLabel('Discord message').locator('option').count();assert.ok(count>1);
  for(let i=0;i<count;i++){await page.getByLabel('Discord message').selectOption(String(i));body=await page.getByLabel('Discord share text').inputValue();assert.ok(body.length<=2000);await button(`Copy message ${i+1}`).click();await button('Copied').waitFor();assert.equal((await app.evaluate(()=>global.__shareClipboard)).text,body);}
  await page.getByLabel('Share introduction').fill('<script>alert(1)</script> A fun collection.');await page.getByRole('tab',{name:'GameBanana'}).click();await page.getByLabel('GameBanana description preview').waitFor();assert.equal(await page.locator('.share-rich-preview script').count(),0);
  await button('Copy formatted description').click();await button('Copied').waitFor();const rich=await app.evaluate(()=>global.__shareClipboard);assert.ok(rich.html.includes('<table>'));assert.ok(!rich.html.includes('<script>'));assert.ok(rich.text.includes('Characters'));assert.ok(rich.text.includes('00:02.0 dialogue time'));
  await button('Copy HTML').click();await button('HTML copied').waitFor();assert.equal((await app.evaluate(()=>global.__shareClipboard)).text,rich.html);
  await page.getByLabel('Share download link').fill('javascript:alert(1)');await page.getByText('Use an http:// or https:// download link without embedded credentials.',{exact:true}).waitFor();assert.equal(await button('Copy formatted description').count(),0);
  await page.getByLabel('Share download link').fill('https://example.com/kung-pow.zip');await page.getByLabel('Share introduction').fill('A scene collection for everyone.');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1120,760));await page.screenshot({path:'.test-data/sharing-gamebanana-small.png'});const size=await page.getByRole('dialog',{name:'Share collection'}).evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));assert.ok(size.scroll<=size.client+1);
  await button('Close dialog').click();await button('Save project').click();await button('Saved').waitFor();const saved=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(saved.shareDetails.downloadUrl,'https://example.com/kung-pow.zip');assert.deepEqual(saved.scenes.map(({name,start,end,clips})=>({name,start,end,clips})),project.scenes.map(({name,start,end,clips})=>({name,start,end,clips})));
  await button('Open').click();await page.locator('.line-row').last().waitFor();await button('Discord').click();assert.equal(await page.getByLabel('Share introduction').inputValue(),'A scene collection for everyone.');await button('Close dialog').click();await button('GameBanana').click();await page.getByRole('tab',{name:'GameBanana',selected:true}).waitFor();await button('Close dialog').click();
  await page.getByLabel('Scene name',{exact:true}).fill('New scene title');await button('Reddit').click();assert.ok((await page.getByLabel('Reddit share text').inputValue()).includes('New scene title'));await page.screenshot({path:'.test-data/sharing-reddit-small.png'});assert.deepEqual(errors,[]);
  console.log('Sharing UI passed: sidebar placement, platform formats, accurate character stats, native clipboard bridge, Discord chunks, escaped HTML, download validation, save/reopen, refreshed scene names and minimum-width layout.');
 }catch(error){const page=await app.firstWindow();console.error(await page.locator('body').innerText());await page.screenshot({path:'.test-data/sharing-failure.png',fullPage:true});throw error;}finally{await app.evaluate(({app})=>app.exit(0));await app.close().catch(()=>{});}
})().catch(e=>{console.error(e);process.exitCode=1;});
