const {_electron:electron}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
const {MediaEngine}=require('../electron/media.cjs');
(async()=>{
  const fixture=JSON.parse(await fs.readFile('.test-data/fixture-path.json','utf8')),data=path.resolve('.test-data','timing-ui-'+Date.now());await fs.mkdir(data,{recursive:true});
  const file=path.join(data,'timing.cvcreator');
  const clips=[{id:'early',caption:'Before trim',character:'A',start:0,end:.2},{id:'selected',caption:'Resize this line',character:'A',start:.4,end:2},{id:'behind',caption:'Overlapping line behind',character:'B',start:1,end:2.5},{id:'late',caption:'After trim',character:'B',start:3.5,end:4}];
  const scene={id:'scene',name:'Timing test',start:2,end:6,clips,backing:{path:fixture.backing,vocalsPath:fixture.backing,duration:4,sourceStart:2,sourceEnd:6,audioIndex:1,reviewed:true},normalize:true};
  await fs.writeFile(file,JSON.stringify({version:1,name:'Timing test',author:'Test',description:'',media:{path:fixture.mkv,duration:8.021,audioIndex:1},scenes:[scene]}));
  const launch=process.env.CV_PACKAGED_EXE?{executablePath:path.resolve(process.env.CV_PACKAGED_EXE),args:[]}:{args:[path.resolve('.')]};
  const app=await electron.launch({...launch,env:{...process.env,CV_TEST_DATA:data}});
  try{
    const page=await app.firstWindow(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
    const button=name=>page.getByRole('button',{name,exact:true});
    const set=async(label,value)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Enter');};
    await page.getByText('FFmpeg ready',{exact:false}).waitFor();
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});dialog.showMessageBox=async()=>({response:1});},file);
    await button('Open').click();await button('Trim scene').waitFor();await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
    assert.equal(await page.locator('.ruler span').first().textContent(),'00:00.000');
    await button('Add dialogue line').click();
    await set('New line start time','00:01.234');await set('New line end time','2.345');
    assert.equal(await page.getByLabel('New line end time',{exact:true}).inputValue(),'00:02.345');
    await set('New line start time','1:99');assert.equal(await page.getByLabel('New line start time',{exact:true}).getAttribute('aria-invalid'),'true');await page.getByLabel('New line start time',{exact:true}).press('Escape');
    assert.equal(await page.getByLabel('New line start time',{exact:true}).inputValue(),'00:01.234');
    await button('Create dialogue line').click();assert.equal(await page.getByLabel('Line start time',{exact:true}).inputValue(),'00:01.234');assert.equal(await page.getByLabel('Line end time',{exact:true}).inputValue(),'00:02.345');
    await button('Undo').click();assert.equal(await page.locator('.line-row').count(),4);
    await page.locator('.line-row').filter({hasText:'Resize this line'}).click();
    const handle=page.locator('[data-clip-id="selected"] .clip-handle.end');await handle.scrollIntoViewIfNeeded();
    const rect=await page.locator('.timeline').boundingBox(),edge=await handle.boundingBox(),x=edge.x+edge.width/2,y=edge.y+edge.height/2;
    assert.equal(await page.evaluate(({x,y})=>document.elementFromPoint(x,y).closest('[data-clip-id]')?.dataset.clipId,{x,y}),'selected');
    assert.equal(await page.locator('[data-clip-id="behind"] .clip-handle').count(),0);
    await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(rect.x+rect.width*2.3/4,y,{steps:8});await page.mouse.up();
    assert.ok(Math.abs(Number((await page.getByLabel('Line end time',{exact:true}).inputValue()).split(':')[1])-2.3)<.02);
    await page.locator('.line-row').filter({hasText:'Overlapping line behind'}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="Line end time"]').value==='00:02.500');
    await button('Undo').click();await page.locator('.line-row').filter({hasText:'Resize this line'}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="Line end time"]').value==='00:02.000');
    await button('Trim scene').click();await set('Trim scene start time','00:01.000');await set('Trim scene end time','00:03.000');
    assert.match(await page.locator('.trim-impact').innerText(),/shortens 1 · removes 2/);
    await page.screenshot({path:'.test-data/trim-scene.png',fullPage:true});
    await button('Cancel trim').click();assert.equal(await page.locator('.line-row').count(),4);
    await button('Trim scene').click();await set('Trim scene start time','1');await set('Trim scene end time','3');await button('Apply trim').click();
    await page.waitForFunction(()=>document.querySelectorAll('.line-row').length===2);assert.equal(await page.locator('.selection-toolbar').count(),0);
    assert.equal(await page.getByRole('checkbox',{name:'I listened and checked the backing track'}).isChecked(),true);
    await button('Save project').click();await button('Saved').waitFor();let saved=JSON.parse(await fs.readFile(file,'utf8'));
    assert.equal(saved.scenes[0].start,3);assert.equal(saved.scenes[0].end,5);assert.deepEqual(saved.scenes[0].clips.map(c=>[c.id,c.start,c.end]),[['selected',0,1],['behind',0,1.5]]);
    const engine=new MediaEngine(path.join(data,'probe'),()=>({}));for(const stem of ['path','vocalsPath']){assert.notEqual(saved.scenes[0].backing[stem],fixture.backing);assert.equal((await engine.probe(saved.scenes[0].backing[stem])).duration,2);}
    await button('Undo').click();assert.equal(await page.locator('.line-row').count(),4);await button('Save project').click();await button('Saved').waitFor();saved=JSON.parse(await fs.readFile(file,'utf8'));assert.equal(saved.scenes[0].backing.path,fixture.backing);assert.equal(saved.scenes[0].start,2);
    await button('Redo').click();await button('Save project').click();await button('Saved').waitFor();await button('Open').click();await page.waitForFunction(()=>document.querySelectorAll('.line-row').length===2);
    await button('Backing track').click();await button('Play').click();await page.waitForFunction(()=>document.querySelector('audio')?.currentTime>.3);await button('Pause').click();
    await button('Trim scene').click();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1120,760));await button('Cancel trim').scrollIntoViewIfNeeded();
    const size=await page.locator('.selection-toolbar').evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth}));assert.ok(size.scroll<=size.client+1);await page.screenshot({path:'.test-data/trim-scene-small.png'});assert.deepEqual(errors,[]);
    console.log('Timing UI passed: scene-relative timecodes/seconds, invalid input, overlapping selected-handle drag, trim summary/cancel/apply, both stems, undo/redo, save/reopen, backing audition and minimum width.');
  }finally{await app.evaluate(({app})=>app.exit(0));await app.close().catch(()=>{});}
})().catch(e=>{console.error(e);process.exitCode=1;});
